export type SavingsOptionGroup = "initial" | "other";
export type ProtectionScheme = "ipab" | "prosofipo" | "none" | "review";
export type ValidationStatus = "verified" | "partial" | "review";

export type SavingsOption = {
  id: string;
  group: SavingsOptionGroup;
  name: string;
  annualRate: number | null;
  currentRate?: number;
  capText: string;
  invested: number | null;
  reportedInterest: number | null;
  reportedTax: number | null;
  requirement: string;
  sheetProtection: ProtectionScheme;
  validatedProtection: ProtectionScheme;
  sheetProtectionLimitUdi: number | null;
  validatedProtectionLimitUdi: number | null;
  sourceUrl: string;
  sourceLabel: string;
  validationStatus: ValidationStatus;
  validationNote: string;
};

export const REFERENCE_SHEET = {
  days: 30,
  udiValue: 8.843769,
  reportedInvestmentTotal: 250000,
  reportedInterestTotal: 2819.66,
  reportedTaxTotal: 77.70,
  reportedWeightedRate: 13.46,
  note: "Captura proporcionada; la fecha del UDI y de las tasas no aparece en la hoja.",
} as const;

export const OFFICIAL_PROTECTION_LIMITS = {
  ipabUdi: 400000,
  prosofipoUdi: 25000,
} as const;

const sources = {
  ipab: "https://www.gob.mx/ipab/articulos/que-son-el-ipab-y-el-seguro-de-depositos-bancarios-311810?idiom=es",
  banxico: "https://www.banxico.org.mx/SieInternet/consultarDirectorioInternetAction.do?accion=consultarCuadro&idCuadro=CP150&sector=8&locale=es",
  fondo: "https://www.fondodeproteccion.mx/",
  plata: "https://bancoplata.mx/es/cuenta",
  uala: "https://www.uala.mx/cuenta-con-rendimiento",
  ualaProducts: "https://www.uala.mx/listado-productos-garantizados",
  openbank: "https://www.openbank.mx/",
  nu: "https://nubank.com.mx/cuenta/rendimientos/",
  klar: "https://klar.mx/cuenta",
  revolut: "https://www.revolut.com/es-MX/",
  didi: "https://didifinance.com/",
  mercadoPago: "https://www.mercadopago.com.mx/",
  mifel: "https://www.mifel.com.mx/personas/cuentas/cuenta-digital",
  now: "https://www.now.bank/cuenta-now",
  kubo: "https://www.kubofinanciero.com/inversiones",
} as const;

// Actualiza esta lista, no el componente, cuando cambien tasas o condiciones.
export const SAVINGS_OPTIONS: SavingsOption[] = [
  {
    id: "didi-base",
    group: "initial",
    name: "DiDi (base)",
    annualRate: 15,
    capText: "$10,000",
    invested: 10000,
    reportedInterest: 125.76,
    reportedTax: 0,
    requirement: "N/A",
    sheetProtection: "prosofipo",
    validatedProtection: "review",
    sheetProtectionLimitUdi: 25000,
    validatedProtectionLimitUdi: null,
    sourceUrl: sources.didi,
    sourceLabel: "DiDi Finanzas",
    validationStatus: "review",
    validationNote: "La página pública consultada muestra crédito, no una cuenta de ahorro; confirmar entidad y protección en el contrato.",
  },
  {
    id: "revolut-base",
    group: "initial",
    name: "Revolut",
    annualRate: 15,
    capText: "$25,000",
    invested: 25000,
    reportedInterest: 314.40,
    reportedTax: 18.50,
    requirement: "Plan 0–4 compras",
    sheetProtection: "ipab",
    validatedProtection: "review",
    sheetProtectionLimitUdi: 400000,
    validatedProtectionLimitUdi: null,
    sourceUrl: sources.revolut,
    sourceLabel: "Revolut México",
    validationStatus: "review",
    validationNote: "La página oficial está disponible, pero no expuso una referencia IPAB verificable en esta revisión; confirmar la entidad mexicana.",
  },
  {
    id: "klar-max",
    group: "initial",
    name: "Klar MAX",
    annualRate: 15,
    capText: "$25,000",
    invested: 25000,
    reportedInterest: 314.40,
    reportedTax: 0,
    requirement: "Gastar $2,500",
    sheetProtection: "prosofipo",
    validatedProtection: "prosofipo",
    sheetProtectionLimitUdi: 25000,
    validatedProtectionLimitUdi: 25000,
    sourceUrl: sources.klar,
    sourceLabel: "Klar",
    validationStatus: "partial",
    validationNote: "Klar confirma la protección del Fondo de Protección y tasas de hasta 15%; la condición específica de $2,500 debe confirmarse en la promoción.",
  },
  {
    id: "uala",
    group: "initial",
    name: "Ualá",
    annualRate: 15,
    capText: "$30,000",
    invested: 30000,
    reportedInterest: 377.27,
    reportedTax: 0,
    requirement: "$6,000 mensuales",
    sheetProtection: "ipab",
    validatedProtection: "ipab",
    sheetProtectionLimitUdi: 400000,
    validatedProtectionLimitUdi: 400000,
    sourceUrl: sources.uala,
    sourceLabel: "Ualá",
    validationStatus: "verified",
    validationNote: "La fuente oficial describe 15% con consumo o nómina de $6,000 y saldo remunerado de hasta $30,000; la oferta tiene vigencia propia.",
  },
  {
    id: "openbank-base",
    group: "initial",
    name: "Openbank",
    annualRate: 13,
    capText: "$30,000",
    invested: 30000,
    reportedInterest: 326.71,
    reportedTax: 0,
    requirement: "N/A",
    sheetProtection: "ipab",
    validatedProtection: "ipab",
    sheetProtectionLimitUdi: 400000,
    validatedProtectionLimitUdi: 400000,
    sourceUrl: sources.openbank,
    sourceLabel: "Openbank México",
    validationStatus: "verified",
    validationNote: "Openbank publica 13% fijo antes de impuestos en los primeros $30,000 y protección IPAB para sus cuentas indicadas.",
  },
  {
    id: "plata-ahorro-ultra",
    group: "initial",
    name: "Ahorro Plata Ultra",
    annualRate: 15,
    capText: "$25,000",
    invested: 25000,
    reportedInterest: 314.40,
    reportedTax: 18.50,
    requirement: "Dura 60 días",
    sheetProtection: "ipab",
    validatedProtection: "ipab",
    sheetProtectionLimitUdi: 400000,
    validatedProtectionLimitUdi: 400000,
    sourceUrl: sources.plata,
    sourceLabel: "Banco Plata",
    validationStatus: "verified",
    validationNote: "Banco Plata publica 15% en los primeros $25,000 por 60 días y protección IPAB; tasa y vigencia pueden cambiar.",
  },
  {
    id: "plata-cuenta",
    group: "initial",
    name: "Plata Cuenta",
    annualRate: 9,
    capText: "N/A",
    invested: null,
    reportedInterest: null,
    reportedTax: null,
    requirement: "$45–$115",
    sheetProtection: "ipab",
    validatedProtection: "ipab",
    sheetProtectionLimitUdi: 400000,
    validatedProtectionLimitUdi: 400000,
    sourceUrl: sources.plata,
    sourceLabel: "Banco Plata",
    validationStatus: "partial",
    validationNote: "La fuente oficial muestra 9% para Ahorro Flexible con Plata+; el requisito de la hoja no se pudo vincular a esa tasa.",
  },
  {
    id: "nu-cajita-turbo",
    group: "initial",
    name: "Nu: Cajita Turbo",
    annualRate: 13,
    capText: "$25,000",
    invested: 25000,
    reportedInterest: 272.26,
    reportedTax: 0,
    requirement: "1 compra",
    sheetProtection: "ipab",
    validatedProtection: "ipab",
    sheetProtectionLimitUdi: 400000,
    validatedProtectionLimitUdi: 400000,
    sourceUrl: sources.nu,
    sourceLabel: "Nu México",
    validationStatus: "partial",
    validationNote: "Nu publica 13% para Cajita Turbo y protección IPAB; el tope de $25,000 y la condición de una compra no aparecen en la fuente consultada.",
  },
  {
    id: "klar-garantia",
    group: "initial",
    name: "Klar garantía",
    annualRate: 13,
    capText: "???",
    invested: 25000,
    reportedInterest: 272.26,
    reportedTax: 0,
    requirement: "Tener tarjeta de crédito",
    sheetProtection: "prosofipo",
    validatedProtection: "prosofipo",
    sheetProtectionLimitUdi: 25000,
    validatedProtectionLimitUdi: 25000,
    sourceUrl: sources.klar,
    sourceLabel: "Klar",
    validationStatus: "partial",
    validationNote: "La protección del Fondo de Protección está documentada; la tasa, el producto y la condición de tarjeta de crédito deben confirmarse.",
  },
  {
    id: "mercado-pago-beneficio",
    group: "initial",
    name: "Mercado Pago (con beneficio)",
    annualRate: 12,
    capText: "$25,000",
    invested: 25000,
    reportedInterest: 251.21,
    reportedTax: 18.50,
    requirement: "Depositar $3,000",
    sheetProtection: "none",
    validatedProtection: "none",
    sheetProtectionLimitUdi: null,
    validatedProtectionLimitUdi: null,
    sourceUrl: sources.mercadoPago,
    sourceLabel: "Mercado Pago",
    validationStatus: "partial",
    validationNote: "Mercado Pago explica que el beneficio combina un componente de Mercado Pago con el rendimiento de un fondo de GBM; no es IPAB.",
  },
  {
    id: "mifel",
    group: "initial",
    name: "Mifel",
    annualRate: 10,
    capText: "$500,000",
    invested: 30000,
    reportedInterest: 251.01,
    reportedTax: 22.20,
    requirement: "N/A",
    sheetProtection: "ipab",
    validatedProtection: "ipab",
    sheetProtectionLimitUdi: 400000,
    validatedProtectionLimitUdi: 400000,
    sourceUrl: sources.mifel,
    sourceLabel: "Banca Mifel",
    validationStatus: "partial",
    validationNote: "Mifel es un banco; la tasa del 10% y el tope de la hoja requieren confirmar el producto y su vigencia.",
  },
  {
    id: "didi-excedente",
    group: "other",
    name: "DiDi (excedente)",
    annualRate: 7,
    capText: "N/A",
    invested: null,
    reportedInterest: 0,
    reportedTax: 0,
    requirement: "N/A",
    sheetProtection: "prosofipo",
    validatedProtection: "review",
    sheetProtectionLimitUdi: 25000,
    validatedProtectionLimitUdi: null,
    sourceUrl: sources.didi,
    sourceLabel: "DiDi Finanzas",
    validationStatus: "review",
    validationNote: "No se encontró una cuenta de ahorro pública que permita confirmar el producto, tasa o protección.",
  },
  {
    id: "revolut-excedente",
    group: "other",
    name: "Revolut (excedente)",
    annualRate: 7,
    capText: "$1,000,000",
    invested: null,
    reportedInterest: 0,
    reportedTax: 0,
    requirement: "N/A",
    sheetProtection: "ipab",
    validatedProtection: "review",
    sheetProtectionLimitUdi: 400000,
    validatedProtectionLimitUdi: null,
    sourceUrl: sources.revolut,
    sourceLabel: "Revolut México",
    validationStatus: "review",
    validationNote: "La cifra de excedente y la protección no se pudieron confirmar con una fuente contractual accesible.",
  },
  {
    id: "klar-flexible",
    group: "other",
    name: "Klar (1 día flexible)",
    annualRate: 8,
    capText: "N/A",
    invested: null,
    reportedInterest: 0,
    reportedTax: 0,
    requirement: "Gastar $2,500",
    sheetProtection: "prosofipo",
    validatedProtection: "prosofipo",
    sheetProtectionLimitUdi: 25000,
    validatedProtectionLimitUdi: 25000,
    sourceUrl: sources.klar,
    sourceLabel: "Klar",
    validationStatus: "partial",
    validationNote: "La protección del Fondo de Protección sí está documentada; la condición de gasto y la modalidad exacta deben confirmarse.",
  },
  {
    id: "openbank-excedente",
    group: "other",
    name: "Openbank (excedente)",
    annualRate: 7,
    capText: "$1,000,000",
    invested: null,
    reportedInterest: 0,
    reportedTax: 0,
    requirement: "N/A",
    sheetProtection: "ipab",
    validatedProtection: "ipab",
    sheetProtectionLimitUdi: 400000,
    validatedProtectionLimitUdi: 400000,
    sourceUrl: sources.openbank,
    sourceLabel: "Openbank México",
    validationStatus: "verified",
    validationNote: "Openbank publica 7% para saldos superiores a $30,000 y hasta $1,000,000 en la información consultada.",
  },
  {
    id: "nu-cajita-247",
    group: "other",
    name: "Nu: Cajita 24/7",
    annualRate: 6.5,
    capText: "N/A",
    invested: null,
    reportedInterest: 0,
    reportedTax: 0,
    requirement: "N/A",
    sheetProtection: "prosofipo",
    validatedProtection: "ipab",
    sheetProtectionLimitUdi: 25000,
    validatedProtectionLimitUdi: 400000,
    sourceUrl: sources.nu,
    sourceLabel: "Nu México",
    validationStatus: "verified",
    validationNote: "La hoja marca PROSOFIPO, pero Nu publica que sus depósitos están protegidos por IPAB; se corrigió la protección mostrada.",
  },
  {
    id: "mercado-pago-base",
    group: "other",
    name: "Mercado Pago (tasa base)",
    annualRate: 5.3,
    capText: "N/A",
    invested: null,
    reportedInterest: 0,
    reportedTax: 0,
    requirement: "N/A",
    sheetProtection: "none",
    validatedProtection: "none",
    sheetProtectionLimitUdi: null,
    validatedProtectionLimitUdi: null,
    sourceUrl: sources.mercadoPago,
    sourceLabel: "Mercado Pago",
    validationStatus: "partial",
    validationNote: "No es un depósito bancario; la tasa base de la hoja no se pudo confirmar en la página pública actual.",
  },
  {
    id: "now-bank",
    group: "other",
    name: "Now Bank",
    annualRate: 7.5,
    currentRate: 7.25,
    capText: "N/A",
    invested: null,
    reportedInterest: 0,
    reportedTax: 0,
    requirement: "N/A",
    sheetProtection: "ipab",
    validatedProtection: "ipab",
    sheetProtectionLimitUdi: 400000,
    validatedProtectionLimitUdi: 400000,
    sourceUrl: sources.now,
    sourceLabel: "Now / INVEX Banco",
    validationStatus: "partial",
    validationNote: "La fuente oficial consultada publica 7.25%, no 7.50%; la protección IPAB sí está documentada.",
  },
  {
    id: "kubo",
    group: "other",
    name: "Kubo",
    annualRate: 13,
    capText: "N/A",
    invested: null,
    reportedInterest: 0,
    reportedTax: 0,
    requirement: "N/A",
    sheetProtection: "prosofipo",
    validatedProtection: "prosofipo",
    sheetProtectionLimitUdi: 25000,
    validatedProtectionLimitUdi: 25000,
    sourceUrl: sources.kubo,
    sourceLabel: "kubo.financiero",
    validationStatus: "partial",
    validationNote: "La entidad se presenta como SOFIPO; confirmar tasa, producto y participación vigente en el Fondo de Protección.",
  },
];

export function roundMoney(value: number) {
  return Math.round(value * 100) / 100;
}

export function calculateSimpleInterest(amount: number, annualRate: number, days: number) {
  return amount * (annualRate / 100) * (days / 365);
}

export function calculateProtectionAmount(udiValue: number, limitUdi: number) {
  return roundMoney(udiValue * limitUdi);
}

export function calculateReferenceValidation(udiValue: number = REFERENCE_SHEET.udiValue, days: number = REFERENCE_SHEET.days) {
  const initial = SAVINGS_OPTIONS.filter((option) => option.group === "initial" && option.invested !== null);
  const investedTotal = initial.reduce((total, option) => total + option.invested!, 0);
  const rowInterestTotal = roundMoney(initial.reduce((total, option) => total + (option.reportedInterest ?? 0), 0));
  const rowTaxTotal = roundMoney(initial.reduce((total, option) => total + (option.reportedTax ?? 0), 0));
  const weightedRate = roundMoney(initial.reduce((total, option) => total + option.invested! * (option.annualRate ?? 0), 0) / investedTotal);
  const simpleInterestTotal = roundMoney(initial.reduce((total, option) => total + calculateSimpleInterest(option.invested!, option.annualRate ?? 0, days), 0));

  return {
    investedTotal,
    rowInterestTotal,
    rowTaxTotal,
    weightedRate,
    simpleInterestTotal,
    rowTotalDifference: roundMoney(rowInterestTotal - REFERENCE_SHEET.reportedInterestTotal),
    simpleInterestDifference: roundMoney(simpleInterestTotal - REFERENCE_SHEET.reportedInterestTotal),
    ipabProtection: calculateProtectionAmount(udiValue, OFFICIAL_PROTECTION_LIMITS.ipabUdi),
    prosofipoProtection: calculateProtectionAmount(udiValue, OFFICIAL_PROTECTION_LIMITS.prosofipoUdi),
  };
}
